spring:
  application:
    name: patronclash-authentication-service

  datasource:
    url: jdbc:postgresql://localhost:5432/patronclash_authentication
    username: ${DB_USERNAME:patronclash_user}
    password: ${DB_PASSWORD:patronclash_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  security:
    jwt:
      secret: ${JWT_SECRET:patronclash-super-secret-key-change-in-production-minimum-256-bits}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in milliseconds
      issuer: patronclash-authentication-service

  # Rate limiting configuration
  rate-limit:
    login:
      capacity: 5
      refill-period: 60 # seconds
      refill-tokens: 5
    general:
      capacity: 100
      refill-period: 60
      refill-tokens: 100

server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api/auth

# Geographic restrictions
geo:
  restriction:
    enabled: ${GEO_RESTRICTION_ENABLED:true}
    allowed-countries: ${ALLOWED_COUNTRIES:US,CA}
    maxmind-db-path: ${MAXMIND_DB_PATH:src/main/resources/GeoLite2-Country.mmdb}

# Logging
logging:
  level:
    com.hintonian.demo.patronclash.authentication: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:DEBUG}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  security:
    enabled: true

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true